export const SET_NAME = "SET_NAME";
export const GET_POSITION = "GET_POSITION";
export const GET_INPUT = "GET_INPUT";
export const TOGGLE_SEARCH_RESULTS = "TOGGLE_SEARCH_RESULTS";
export const GET_ADDRESS_PREDICTIONS = "GET_ADDRESS_PREDICTIONS";
export const GET_SELECTED_ADDRESS = "GET_SELECTED_ADDRESS";
